### ISSUE TITLE
The SCORM course does not start

### ISSUE THREAD

**Issue by aidemkin** [frappe/lms#1153]
**Describe the bug**

I follow the steps as shown in the [issue](https://github.com/frappe/lms/issues/1082), but when I click on the successfully downloaded chapter of the SCORM course, the file is downloaded. When performing such actions, the course is expected to start. I updated to the latest release, tested in different browsers.

**To Reproduce**
1. Go to 'LMS'
2. Click on menu 'Courses'
3. Click on button '+ New'
4. Fill in the required fields with arbitrary data
5. Click on button 'Save'
6. Click on button 'Add Chapter'
7. Fill in the title field test data
8. Activate the "SCORM Package" switch and select the SCORM file from the issue
9. Wait for the full upload and click on button 'Create'
10. Go to the created course and click on the chapter with the SCORM package 
11. See error - the "indexAPI.html" file is downloaded to the computer and the course does not play. The name of the downloaded file differs depending on the SCORM file

**Expected behavior**
Waiting for the SCORM course playback to start

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome, safari
 - Release LMS: v2.13.0

**Comment by FahidLatheef** [comment]
Interestingly, SCORM chapters are properly loading in the local dev setup with honcho.

However, in the production setup (Tried with docker and bare metal prod setup), the above issue is arising.

My guess is that, it is something to do with how Nginx serves the site.

@aidemkin Can you mention the type of the setup you are using?

**Comment by aidemkin** [comment]
@FahidLatheef hi!

I use private frappe cloud

**Comment by FahidLatheef** [comment]
This is the line where LMS renders SCORM chapter.
https://github.com/frappe/lms/blob/develop/frontend/src/pages/SCORMChapter.vue#L15

When I checked the network tab, there is a custom response header `Content-disposition` with the value `attachment` is added in Nginx-based setups, which is causing the file to download automatically.

I did some research. The below highlighted lines in Nginx Conf of Frappe Docker adds the aforementioned custom header
https://github.com/frappe/frappe_docker/blob/main/resources/nginx-template.conf#L53C1-L56C4.

I commented it out and restarted nginx. Now the lms_scorm.html redirects to page lms_scorm. This is due to the below highlighted lines.
https://github.com/frappe/frappe_docker/blob/main/resources/nginx-template.conf#L50C1-L52C1

I commented them out as well and now SCORM **works correctly** with Nginx based setups.

@pateljannat, need your input here for tackling this issue.

**Comment by pateljannat** [comment]
@FahidLatheef @aidemkin I am in touch with the Frappe Cloud team to fix this. Will let you guys know when its resolved.

**Comment by pateljannat** [comment]
@FahidLatheef Removing 'Content-Disposition" "attachments" won't work as this is in place for security and removing that makes the system susceptible to security threats.

**Comment by pateljannat** [comment]
I am planning to change the implementation to a SCORM Cloud integration

**Comment by aidemkin** [comment]
Do I understand correctly that this implementation option cannot be applied
to large clients who use LMS on private servers within the company without
Internet access?

чт, 5 дек. 2024 г. в 15:17, Jannat Patel ***@***.***>:
