### ISSUE TITLE
A Social Learning Platform

### ISSUE THREAD

**Issue by pateljannat** [frappe/lms#283]
**Issue:**

We started this app with a vision to have a Social Learning platform, where people not just learn but interact with each other and get a sense of a community. Over the past few months, the app has grown on the learning side. It has the basic features that a learning platform should have. But the social aspect is still missing. Without that, the learning gets isolating. No matter the amount of effort that maintainers put into the platform, users need something more that will make them want to come back. Whereas if the users interact as a community, they may come up with things on their own to ensure that the platform survives. The problem at hand is not the communication medium. It's who should the user communicate with. Right now the platform does not provide any visibility about its users.

**Solution 1: Members Page**

A link on the course home page that leads to the Members page. This page will list down the users that have enrolled for that particular course.

**Pros:** If I am a user of Frappe School enrolled in a course for the Manufacturing domain, this page would show other people who have taken the same course. As a result, I get to know more people from the Manufacturing community.
Similarly, if I am a user of Mon School enrolled in a course for Django, I get to know more people from the Django community.

**Cons:** As the number of people enrolled in a course increase, the page might lead to an endless scroll. Also, this requires clicking on user cards to see their detailed profile page. 

**Solution 2: Community Page**

A search page like LinkedIn, where users enter certain keywords. These keywords then get searched for in certain important fields like user's name, work experience, education, skills, etc. Accordingly the search results get displayed. 

**Pros:** Ensures a more refined search

**Cons:** Users need to enter some input before they see any results on the page.

**cc:** @rmehta, @anandology, @asbasawaraj 
Would like to hear your thoughts.

**Comment by anandology** [comment]
What if we repurpose the discussions to enable communication between students. Rather than having discussions per lesson, keep the discussions by course and allowing tagging people in discussions. There could be a discussion thread on Introductions, or a thread on who is hiring in Jan 2022 etc. 

We can have a tags for discussions and all the questions can be tagged as "Question" and all the hiring related discussions can be tagged as "Hiring" and students can subscribe to a tag to get notified on any new activity on that topic.

The discussion page can show the list of member who recently participated in the discussions. That way we only show the people who are actively engaging right now rather than all people who have completed the course ever since.

**Comment by anandology** [comment]
It would be interesting to see if we can make the discussions site-wide while still making it easier to ask questions about a course.

**Comment by anandology** [comment]
With the both the solutions that @pateljannat has suggested, it will be possible to search and find for people, but the only action the can be done is following their linkedin profile or contact them offline. I feel we need to enable communication in side the system and enriching the discussions to support that would be an interesting way, IMHO.
