### ISSUE TITLE
LMS Settings: Make LMS the default home

### ISSUE THREAD

**Issue by SteveSimonson** [frappe/lms#727]
We have tried to use the LMS setting of making the LMS the home page, but perhaps we're not using it correctly.

![Screenshot 2024-01-22 at 1 18 56 PM](https://github.com/frappe/lms/assets/144349219/61cef48a-1668-46fa-9197-9186d5375bc0)

**To Reproduce**
1. Go to LMS Settings page
2. Click on the Make LMS the default home
3. We then test training.parsimony.com 
4. But the site still resolves to the /me page rather than the expected home of the /courses

This is where the site is going to by default:

![Screenshot 2024-01-22 at 1 21 29 PM](https://github.com/frappe/lms/assets/144349219/1efacb2c-9e83-497d-aab0-71b981863c01)

We thought the setting would make the default page this:

![Screenshot 2024-01-22 at 1 22 24 PM](https://github.com/frappe/lms/assets/144349219/74abe4b9-ff75-4a6c-9997-ad5b0d2825a7)

Perhaps this is linked to our own DNS settings since we're using a subdomain, but the network engineers say that it's not the DNS.

Your wisdom would be valuable.

We love the LMS. 

We're building free courses on it to help the community too. :)

**Comment by pateljannat** [comment]
@SteveSimonson, I'm glad you love the app and use it for good purposes. Your site is not on our cloud. I would need you to give me access to check the issue. I have signed up to the site using the email jannat@frappe.io. Would you be able to give this user System Manager role

**Comment by SteveSimonson** [comment]
@pateljannat Howdy

We wanted to host on your cloud, but after several inquires if we could host on our own domain, we decided to spin up our own server.

We think what you're doing is awesomer!

I have made you a system manager.

**Comment by SteveSimonson** [comment]
@pateljannat Let me know if you have time this week to check it out. :)

**Comment by praneetloke** [comment]
Sorry for commenting on such an old issue. But I stumbled on this issue while trying to figure out how to redirect students after a login. I've solved that now. However, since the courses page is accessed at `/lms`, if a student simply types the base URL for my LMS site, they land on the profile page as shown in the original post above. I am a Frappe Cloud user.

This is what they see if a student user goes to the platform URL without typing `/lms`. As I said above, after a login, they are redirected, but during subsequent visits, they navigate to the base URL and are left at this page without any information about how to get to the courses page.

<img width="836" height="618" alt="Image" src="https://github.com/user-attachments/assets/f13a1ff5-7c32-4d09-97ae-5d279ec25dad" />

Is there a way to add a link to the Courses page that shows up on this profile page? By the way, click Home does nothing and clicking Desktop fails because they are not authorized to view the Desk app.
